// 외부 라이브러리를 앱 번들에 포함한다 (2026-09-07, P0 속도).
// 전에는 unpkg(lucide@latest)·jsdelivr(flatpickr 3파일·luxon)에서 매 방문 받아왔다.
// @latest는 매번 302 리다이렉트를 타고 캐시도 짧아, 외부 도메인 5개 왕복이 첫 화면을 붙잡았다.
// 화면 코드는 window.luxon / window.flatpickr / window.lucide 전역을 그대로 쓰므로
// 여기서 같은 이름으로 걸어 준다 — 화면 코드 무변경.
import * as luxon from 'luxon';
import flatpickr from 'flatpickr';
import { Korean } from 'flatpickr/dist/l10n/ko.js';
import 'flatpickr/dist/flatpickr.min.css';
import {
  createIcons,
  Activity,
  AlertCircle,
  ArrowLeft,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  CloudSun,
  Copy,
  Folder,
  FolderKanban,
  FolderX,
  GripVertical,
  Heart,
  Home,
  Hourglass,
  Inbox,
  Info,
  Layers,
  Lightbulb,
  ListChecks,
  Loader,
  Loader2,
  Minus,
  Moon,
  PenSquare,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Users,
  X,
} from 'lucide';

// 쓰는 아이콘만 이름으로 가져온다(트리셰이킹). `icons` 전체 객체를 가져오면 3,600개가 다 번들에 들어간다(850KB, 실측).
// data-lucide="kebab-name"은 lucide가 PascalCase로 바꿔 아래 객체에서 찾는다.
// 새 아이콘을 화면에 넣으면 위 import와 아래 객체에 추가한다 — 빠지면 콘솔에 "icon name was not found" 경고가 뜨고 빈 자리로 남는다.
const icons = {
  Activity,
  AlertCircle,
  ArrowLeft,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  CloudSun,
  Copy,
  Folder,
  FolderKanban,
  FolderX,
  GripVertical,
  Heart,
  Home,
  Hourglass,
  Inbox,
  Info,
  Layers,
  Lightbulb,
  ListChecks,
  Loader,
  Loader2,
  Minus,
  Moon,
  PenSquare,
  Pencil,
  Pin,
  Plus,
  RefreshCw,
  Repeat,
  RotateCcw,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Sunrise,
  Target,
  Trash2,
  TrendingDown,
  TrendingUp,
  Users,
  X,
};

flatpickr.localize(Korean);

window.luxon = luxon;
window.LUXON_LOADED = true;
window.flatpickr = flatpickr;
window.lucide = {
  createIcons: (opts = {}) => createIcons({ icons, ...opts }),
  icons,
};
